### ISSUE TITLE
Cannot import the package in Anki after running Ankdown with method A

### ISSUE THREAD

**Issue by oskarryn** [benwr/ankdown#20]
I follow the method A to create a package. 

An error occurs when importing the package with the Anki import tool:

> Selected file was not in UTF-8 format. Please see the importing section of the manual.

The directory specified after `-r` has only one file which is a copy-paste of the cards example from README.

Tried out on Anki 2.1.11-1 and Anki 2.1.13 (dev).

Is `ankdown` supposed to produce files in UTF-8 format? When I run `file -i package` I can see `charset=binary`, so the output I get from `ankdown` isn't UTF-8.

**Comment by benwr** [comment]
it isn't meant to be text; it's supposed to be a .apkg file. Anki should be able to load it if you select "Packaged anki deck / collection" at the import selection screen.

**Comment by benwr** [comment]
This should be more clear in the README; thanks for reporting it.

**Comment by oskarryn** [comment]
It works thanks!

Yes adding that the package must have extension `.apkg` would have spared my embarrassment here. New to Anki.
