### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by mainrs** [benwr/ankdown#4]
I am using a lot of mnemonics for my flash cards and audio files. Does ankdown support them? And if yes, how would I add them to my flash cards?

**Comment by dzackgarza** [comment]
Had the same question here - I haven't tried it yet, but it looks like perhaps HTML image tags might work, as per this section in the code: https://github.com/benwr/ankdown/blob/38839a0f1d3e4c1c4040c5142b1ea2827d325cfe/ankdown/ankdown.py#L157

Might be possible to modify this to look for the usual markdown image tags, not sure!

**Comment by benwr** [comment]
Yes, images should work - if they don't, feel free to reopen this issue.
